# Generated by Django 5.2.12 on 2026-03-26 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymovie', '0005_season_episode_webseries_seriesreview_seriescrew_and_more'),
        ('mypayment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='webseries',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mymovie.webseries'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mymovie.movie'),
        ),
    ]
