# Generated by Django 5.2.12 on 2026-03-15 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_name', models.CharField(max_length=200)),
                ('act_image', models.ImageField(upload_to='actors/')),
                ('act_birth_date', models.DateField(blank=True, null=True)),
                ('act_bio', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew_name', models.CharField(max_length=200)),
                ('crew_role', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mov_name', models.CharField(max_length=200)),
                ('mov_genre', models.CharField(max_length=100)),
                ('mov_year', models.IntegerField()),
                ('mov_duration', models.CharField(max_length=20)),
                ('mov_description', models.TextField()),
                ('mov_banner', models.ImageField(upload_to='movies/')),
                ('mov_rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plat_name', models.CharField(max_length=100)),
                ('plat_logo', models.ImageField(upload_to='platforms/')),
            ],
        ),
        migrations.CreateModel(
            name='MovieCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast_order', models.IntegerField(default=0)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymovie.actor')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymovie.character')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casts', to='mymovie.movie')),
            ],
            options={
                'ordering': ['cast_order'],
            },
        ),
        migrations.CreateModel(
            name='MovieCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymovie.crew')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crews', to='mymovie.movie')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='mov_platforms',
            field=models.ManyToManyField(blank=True, to='mymovie.platform'),
        ),
    ]
