# Generated by Django 5.2.12 on 2026-03-20 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymovie', '0003_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='blog',
            new_name='movie',
        ),
    ]
