# Generated by Django 5.2.12 on 2026-03-23 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymovie', '0004_rename_blog_review_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.IntegerField()),
                ('episode_title', models.CharField(max_length=200)),
                ('episode_duration', models.CharField(max_length=20)),
                ('episode_description', models.TextField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='mymovie.season')),
            ],
        ),
        migrations.CreateModel(
            name='WebSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(max_length=200)),
                ('series_genre', models.CharField(max_length=100)),
                ('series_start_year', models.IntegerField()),
                ('series_end_year', models.IntegerField(blank=True, null=True)),
                ('series_description', models.TextField()),
                ('series_banner', models.ImageField(upload_to='series/')),
                ('series_rating', models.FloatField()),
                ('languages', models.ManyToManyField(blank=True, to='mymovie.language')),
                ('platforms', models.ManyToManyField(blank=True, to='mymovie.platform')),
            ],
        ),
        migrations.CreateModel(
            name='SeriesReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_name', models.CharField(max_length=100)),
                ('review_rating', models.FloatField()),
                ('review_msg', models.TextField()),
                ('review_created_at', models.DateTimeField(auto_now_add=True)),
                ('webseries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='mymovie.webseries')),
            ],
        ),
        migrations.CreateModel(
            name='SeriesCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymovie.crew')),
                ('webseries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crews', to='mymovie.webseries')),
            ],
        ),
        migrations.CreateModel(
            name='SeriesCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast_order', models.IntegerField(default=0)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymovie.actor')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymovie.character')),
                ('webseries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casts', to='mymovie.webseries')),
            ],
            options={
                'ordering': ['cast_order'],
            },
        ),
        migrations.AddField(
            model_name='season',
            name='webseries',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='mymovie.webseries'),
        ),
    ]
