# Generated by Django 5.2.12 on 2026-03-26 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymovie', '0006_watchlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('user', 'movie')},
        ),
        migrations.AddField(
            model_name='watchlist',
            name='webseries',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mymovie.webseries'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mymovie.movie'),
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('user', 'movie'), ('user', 'webseries')},
        ),
    ]
