# Generated by Django 5.2.12 on 2026-03-27 05:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymovie', '0008_contactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='message_sent',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
