# Generated by Django 5.2.12 on 2026-06-07 15:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymovie', '0009_contactform_message_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='act_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
