# Generated by Django 5.2.12 on 2026-06-07 15:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymovie', '0010_alter_actor_act_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='act_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
